### ISSUE TITLE
Add delete table functionality

### ISSUE THREAD

**Issue by Mohit-Chaudhari** [NikitaChandore/NIKIDB#20]
1. Add delete table functionality into the project.
2. Example : del tb <table_name>
3. After deletion of table, remove it's entry from TABLE_INFO.
4. Add it's entry in TABLE_HISTORY file with some parameters like,
    i. Table name
    ii. Table creation date.
    iii. Table creation time.
    iv. Table deletion date.
    v. Table deletion time.
    vi. Database name from which table get deleted.

@NikitaChandore Please add your suggestion regarding this feature.

**Comment by NikitaChandore** [comment]
1.while deleting a table we also need to handle the hierarchy like if table1 is under database D then if user want to restore details about table1 then we have to put that details under the same hierarchy.
same for database if we delete a database then there may be some tables under that specific table so while restoring database details all those details about table also needs to get restore.
so i think we should introduce new functionality for restoring data

**Comment by Mohit-Chaudhari** [comment]
Task completed with following changes,
1. In NIKI_INITIALISE module while initialising default database, the database related information get feed into DATABASE_INFO.
2. NIKI_COMMAND_DRIVER module's code updated to enable delete table feature.
3. New method NIKI_GET_DB_ID added into NIKI_NEURAL_HUB module to get current using database id.
4. NIKI_DEL_TB method defined in NIKI_TABLE_HANDLER module to perform table deletion operation.
5. NIKI_TABLE_ENTRY_REMOVER method added into NIKI_TABLE_JSON_HANDLER module which will remove the table entry from TABLE_INFO after table deletion process get's completed.
6. NIKI_TABLE_HISTORY_UPDATOR method added into NIKI_TABLE_JSON_HANDLER module to update the deleted table entry into TABLE_HISTORY_INFO which is located in LOGS package.

Please refer pull request for more info : https://github.com/NikitaChandore/NIKIDB/pull/22

@NikitaChandore Please review pull request and merge it to master branch.
